server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/neardeal?serverTimezone=Asia/Seoul&characterEncoding=utf8&useUnicode=true
    username: root
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO_VALUE}
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB

springdoc:
  packages-to-scan: hello.neardeal_server
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  api-docs:
    path: /api-docs/json
    groups:
      enabled: true
  swagger-ui:
    enabled: true
    path: /swagger
    tags-sorter: alpha
    operations-sorter: method

file:
  path: ${FILE_PATH:/app/nearDealImage}

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web.cors: TRACE # CORS ?? ??? TRACE ??? ? ???? ??